import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {test} from 'node:test';
import assert from 'node:assert/strict';
const out=path.resolve('.test-build');fs.mkdirSync(out,{recursive:true});
for(const name of ['catalog','engine','demo','retrieval']){let source=fs.readFileSync(`lib/${name}.ts`,'utf8');let js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/from '(\.\/\w+)'/g,"from '$1.mjs'");fs.writeFileSync(path.join(out,`${name}.mjs`),js);}
const {evaluate,precision,parseRows,allowable,sd}=await import('../.test-build/engine.mjs');const {makeDraft,demoData,demoRecords}=await import('../.test-build/demo.mjs');
const close=(a,b,t=1e-10)=>assert.ok(Math.abs(a-b)<t,`${a} ≠ ${b}`);
test('Sample SD uses n−1',()=>close(sd([1,2,3,4,5]),Math.sqrt(2.5)));
test('ANOVA independent hand-calculated variance components',()=>{const p=precision([[1,2,3],[2,3,4]]);close(p.mean,2.5);close(p.repeatSD,1);close(p.betweenSD,Math.sqrt(1/6));close(p.withinSD,Math.sqrt(7/6));});
test('Negative between-day variance clamped at zero',()=>{const p=precision([[1,2,3],[1,2,3]]);close(p.betweenSD,0);close(p.withinSD,1);assert.equal(p.negativeVariance,true);});
test('Reject unbalanced design',()=>assert.throws(()=>precision([[1,2],[1,2,3]])));
test('Vietnamese decimal commas and tab columns',()=>assert.deepEqual(parseRows('0,51; 0,52\n0,50\t0,49'),[[.51,.52],[.5,.49]]));
test('Never silently drops malformed tokens',()=>{for(const value of ['1; abc','1,,2','1,2,3','1; NaN','1; Infinity','1e500'])assert.throws(()=>parseRows(value));});
test('FT4 CLIA absolute limit dominates at low concentration',()=>{close(allowable('FT4','ng/dL',.5),60);close(allowable('FT4','ng/dL',4),15);});
test('Supported conversion preserves FT4 TEa',()=>close(allowable('FT4','pmol/L',6.435),60));
test('Unknown analyte or incompatible unit never guesses TEa',()=>{assert.equal(allowable('FT4','ng/mL',.5),null);assert.equal(allowable('Unknown','mg/dL',100),null);});
test('Complete synthetic FT4 study passes chosen direct-comparison criteria',()=>{const r=evaluate(makeDraft('dxi-local-ft4',true));assert.equal(r.status,'pass');assert.equal(r.levels.length,3);assert.equal(r.levels[0].n,100);});
test('Insufficient number of days blocks conclusion',()=>{const d=makeDraft(undefined,true);d.levels[0].data=d.levels[0].data.split('\n').slice(0,5).join('\n');assert.equal(evaluate(d).status,'insufficient');});
test('Known manufacturer profile cannot be silently modified',()=>{const d=makeDraft(undefined,true);d.levels[0].repeatLimit=100;assert.equal(evaluate(d).status,'insufficient');});
test('Wrong machine automation and assay block reused profile',()=>{for(const field of ['instrument','automation','assay','unit']){const d=makeDraft(undefined,true);d[field]=field==='automation'?'manual':'Other';assert.equal(evaluate(d).status,'insufficient');}});
test('No fabricated pass for zeros or no variation',()=>{const d=makeDraft(undefined,true);d.levels[0].data=Array.from({length:20},()=>'.51; .51; .51; .51; .51').join('\n');assert.equal(evaluate(d).status,'insufficient');d.levels[0].data='0;0\n0;0';assert.equal(evaluate(d).status,'insufficient');});
test('Inflated variability fails',()=>{const d=makeDraft(undefined,true);d.levels=d.levels.map(l=>({...l,data:demoData(l.target,5)}));assert.equal(evaluate(d).status,'fail');});
test('Trueness uses target QC, not manufacturer study mean',()=>{const d=makeDraft(undefined,true);d.levels[0].target=.6;const r=evaluate(d);close(r.levels[0].biasPercent,(r.levels[0].mean-.6)/.6*100);});
test('MU is absent without target uncertainty and bias handling',()=>{const d=makeDraft(undefined,true);assert.equal(evaluate(d).levels[0].u,null);d.levels[0].uReference=.002;d.levels[0].biasCorrected=true;assert.ok(evaluate(d).levels[0].u>0);});
test('Qualitative denominators distinguish false positives and false negatives',()=>{const d=makeDraft(undefined,true);d.study='qualitative';d.extras={...d.extras,tp:18,fn:2,fp:4,tn:16,sensitivity:80,specificity:80};const r=evaluate(d);close(r.metrics.sensitivity,90);close(r.metrics.specificity,80);close(r.metrics.falsePositive,20);close(r.metrics.falseNegative,10);});
test('Reject fractional and negative sample counts',()=>{const d=makeDraft(undefined,true);d.extras.tp=2.2;assert.throws(()=>evaluate(d));d.extras.tp=-1;assert.throws(()=>evaluate(d));});
test('Reference boundary 18/20 uses documented internal interpretation',()=>{const d=makeDraft(undefined,true);d.study='reference';d.extras.lower=1;d.extras.upper=2;d.extras.data=[...Array(18).fill(1.5),0,3].join('\n');assert.equal(evaluate(d).status,'pass');});
test('R squared of one cannot automatically certify agreement',()=>{const d=makeDraft(undefined,true);d.study='comparison';d.extras.data=Array.from({length:40},(_,i)=>`${i+1};${2*(i+1)}`).join('\n');const r=evaluate(d);close(r.metrics.rSquared,1);assert.equal(r.status,'insufficient');assert.equal(r.criteria[0].pass,false);});
test('LoD uses detection above blank, never below claimed LoD',()=>{const d=makeDraft(undefined,true);d.study='lod';d.extras.data=Array(20).fill(.001).join('\n');assert.equal(evaluate(d).metrics.detection,0);assert.equal(evaluate(d).status,'insufficient');});
test('Malformed/null input rejected intentionally',()=>{assert.throws(()=>evaluate({}));assert.throws(()=>evaluate(null));const d=makeDraft(undefined,true);d.sourceUrl='javascript:alert(1)';assert.throws(()=>evaluate(d));});
test('Twelve demo records are explicitly synthetic and computed',()=>{assert.equal(demoRecords.length,12);assert.ok(demoRecords.every(r=>r.sample));assert.ok(demoRecords.filter(r=>r.status==='approved').every(r=>r.evaluation.status==='pass'));});
