'use client';
import {useEffect,useRef,useState} from 'react';
import {knowledge,sourceNotes} from '@/lib/catalog';
import {inScope} from '@/lib/retrieval';
import {Sparkles,Search,ShieldCheck,Check,X,BookOpen} from 'lucide-react';
import {PanelTitle} from './ui';
const corpus=[...knowledge.map(k=>({...k,source:'XN-QTQL-16 · bản tóm lược đã đối chiếu'})),...sourceNotes.map((s,i)=>({id:'source-'+i,title:s.title,text:s.body,source:'Ghi chú đối chiếu nguồn'}))];
function normalize(s:string){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();}
export default function Assistant({onAccept}:{onAccept?:(s:string)=>void}){const [q,setQ]=useState('Cần bao nhiêu ngày để đánh giá độ chụm?'),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[items,setItems]=useState<any[]>([]),[draft,setDraft]=useState(''),[kind,setKind]=useState('');const worker=useRef<Worker|null>(null);
useEffect(()=>()=>worker.current?.terminate(),[]);
function search(ai:boolean){setDraft('');setItems([]);if(q.trim().length<3){setStatus('Nhập câu hỏi ít nhất 3 ký tự.');return;}if(!inScope(q)){setStatus('Ngoài phạm vi: trợ lý chỉ tra cứu quy trình kiểm tra xác nhận phương pháp xét nghiệm.');return;}
if(!ai){const words=normalize(q).split(/\W+/).filter(w=>w.length>2);const matches=corpus.map(c=>({...c,score:words.reduce((s,w)=>s+(normalize(c.title+' '+c.text).includes(w)?1:0),0)})).filter(c=>c.score>0).sort((a,b)=>b.score-a.score).slice(0,3);setItems(matches);setKind('Tra cứu từ khóa');setStatus(matches.length?'Đã tìm thấy các đoạn liên quan.':'Chưa tìm thấy trong kho quy trình.');return;}
setBusy(true);setKind('AI tra cứu ngữ nghĩa');setStatus('Chuẩn bị mô hình. Lần đầu có thể mất vài phút…');
if(!worker.current){worker.current=new Worker(new URL('../lib/ai.worker.ts',import.meta.url),{type:'module'});worker.current.onmessage=e=>{const d=e.data;if(d.type==='progress')setStatus(d.message);if(d.type==='result'){setItems(d.items);setBusy(false);setStatus(d.items.length?'AI đã chọn các đoạn liên quan. Hãy đối chiếu nguồn trước khi sử dụng.':'Không tìm thấy đoạn đủ liên quan. Thử câu hỏi khác.');}if(d.type==='error'){setBusy(false);setStatus('Chưa chạy được mô hình trên thiết bị. Bạn vẫn có thể tra cứu bằng từ khóa.');}};worker.current.onerror=()=>{setBusy(false);setStatus('Không tải được AI. Kiểm tra kết nối hoặc dùng tìm từ khóa.');worker.current?.terminate();worker.current=null;};}
worker.current.postMessage({query:q});}
return <section className="panel assistant-panel"><PanelTitle title="Tra cứu quy trình bằng AI" subtitle="Tìm ngữ nghĩa tiếng Việt trong các đoạn hướng dẫn có nguồn" icon={<Sparkles size={22}/>}/><div className="callout neutral compact"><ShieldCheck size={20}/><p>Mô hình MiniLM đa ngôn ngữ chạy trong trình duyệt. Lần đầu cần tải mô hình từ Hugging Face; câu hỏi và số đo không gửi tới dịch vụ suy luận. AI chỉ chọn đoạn văn, không quyết định kết quả chuyên môn.</p></div><label>Câu hỏi về quy trình<textarea rows={2} maxLength={500} value={q} onChange={e=>setQ(e.target.value)} placeholder="Ví dụ: CV vượt công bố thì cần làm gì?"/></label><div className="button-row"><button className="primary" disabled={busy} onClick={()=>search(true)}><Sparkles size={17}/>{busy?'Đang xử lý…':'Tra cứu bằng AI'}</button><button className="secondary" disabled={busy} onClick={()=>search(false)}><Search size={16}/> Tìm từ khóa</button>{busy&&<button className="text-button" onClick={()=>{worker.current?.terminate();worker.current=null;setBusy(false);setStatus('Đã dừng mô hình.');}}>Dừng</button>}</div><p role="status" className="assistant-status">{status}</p>{items.map(item=><div className="retrieved" key={item.id}><div><BookOpen size={18}/><h3>{item.title}</h3><span>{kind}</span></div><p>{item.text}</p><small>Nguồn: {item.source}{kind.startsWith('AI')?` · Điểm tìm kiếm ${item.score.toFixed(2)} (không phải độ tin cậy)` : ''}</small><button className="text-button" onClick={()=>setDraft(`${item.text}\nNguồn: ${item.source}`)}>Dùng làm bản nháp ghi chú</button></div>)}{draft&&<div className="assistant-draft"><label>Kiểm tra và chỉnh sửa bản nháp<textarea rows={5} value={draft} onChange={e=>setDraft(e.target.value)}/></label><div className="button-row"><button className="primary" onClick={()=>{onAccept?.(draft);setStatus(onAccept?'Đã đưa nội dung đã kiểm tra vào ghi chú hồ sơ.':'Đã chấp nhận bản nháp tại phiên tra cứu này. Sao chép nội dung để đưa vào hồ sơ.');setDraft('');}}><Check size={16}/>Chấp nhận nội dung</button><button className="secondary" onClick={()=>setDraft('')}><X size={16}/>Bỏ bản nháp</button></div></div>}<a className="source-link" href="https://huggingface.co/Xenova/paraphrase-multilingual-MiniLM-L12-v2" target="_blank" rel="noreferrer">Thông tin mô hình AI</a></section>;
}

